# Generated by Django 3.2.6 on 2023-11-22 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default=1, max_length=150, verbose_name='Author'),
            preserve_default=False,
        ),
    ]
