# Generated by Django 3.2.6 on 2023-11-22 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default=1, max_length=150, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
